name: example-servant-minimal

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - example-servant-minimal
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types
      - read-env-var

library:
  source-dirs:
    - src

executables:
  example-servant-minimal:
    main: exe/Main.hs
    dependencies:
      - example-servant-minimal

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - aeson
  - wai
  - warp
  - read-env-var
